### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by PaddyLevitt** [PaddyLevitt/Capstone2016PhotoShare#2]
When trying to register with all other fields entered correctly, if Full Name field contains spaces between names the screen locks and nothing happens.

**Comment by wheelburra** [comment]
Didn't know about this bug. Will mull over possible solutions. Maybe we
could just do two separate fields for first and last name or just add an
underscore for the space like in the create album function

Alexander Barrow

**Comment by PaddyLevitt** [comment]
Formatted String to add a plus character '+' where spaces would be before sending in URL as parameter. This fixes the issue as the plus char in URLs is used to represent spaces. Also added features to make sure user cannot try to send a username or password containing spaces.

**Comment by wheelburra** [comment]
Nice catch/fix

Alexander Barrow
